spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}  # 실제 아이디 대신 환경 변수를 사용하세요.
    password: ${SPRING_DATASOURCE_PASSWORD}  # 실제 비밀번호 대신 환경 변수를 사용하세요.
    driver-class-name: com.mysql.cj.jdbc.Driver

#crypto:
#  secret-key: ${CRYPTO_KEY}
#  init-vector: ${CRYPTO_INIT_VECTOR}
#
#jwt:
#  secret-key: ${JWT_SECRET_KEY}