spring:
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
jwt:
  secret-key: ${JWT_SECRET_KEY}
#crypto:
#  secret-key: ${CRYPTO_KEY}
#  init-vector: ${CRYPTO_INIT_VECTOR}
